export const projects = [
  {
    id: 1,
    title: 'Fish',
    date: '2020-07-01',
    tech: ['Typescript', 'Node'],
    description:
      'lorLorem, ipsum dolor sit amet consectetur adipisicing elit. Vitae quisquam iste tempora, quas eos, sit quam aut animi non blanditiisem',
    img: 'https://images.unsplash.com/photo-1560275619-4662e36fa65c?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjR8fGZpc2h8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    src: '#project-demo',
    src_github: '#project-github',
  },
  {
    id: 2,
    title: 'Mamal',
    date: '2020-08-01',
    tech: ['Typescript', 'Node'],
    description:
      'consectetur adipisicing elit. Vitae quisquam iste tempora, quas eos, sit quam aut animi non blanditiisem',
    img: 'https://images.unsplash.com/photo-1603897178457-f87e0bf8fd53?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjV8fG1hbWFsfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    src: '#project-demo',
    src_github: '#project-github',
  },
  {
    id: 3,
    title: 'Bird',
    date: '2020-11-01',
    tech: ['Typescript', 'Node'],
    description: 'Vitae quisquam iste tempora, quas eos, sit quam aut animi non blanditiisem',
    img: 'https://images.unsplash.com/photo-1522926193341-e9ffd686c60f?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8YmlyZHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    src: '#project-demo',
    src_github: '#project-github',
  },
  {
    id: 4,
    title: 'Reptile',
    date: '2020-12-01',
    tech: ['Typescript', 'Node'],
    description: 'lorLorem, ipsumam aut animi non blanditiisem',
    img: 'https://images.unsplash.com/photo-1621327887409-fb4302a3b050?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTF8fHJlcHRpbGV8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    src: '#project-demo',
    src_github: '#project-github',
  },
  {
    id: 5,
    title: 'Fish',
    date: '2021-02-01',
    tech: ['Typescript', 'Node'],
    description:
      'lorLorem, ipsum dolor sit amet consectetur adipisicing elit. Vitae quisquam iste tempora, quas eos, sit quam aut animi non blanditiisem',
    img: 'https://images.unsplash.com/photo-1560275619-4662e36fa65c?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjR8fGZpc2h8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    src: '#project-demo',
    src_github: '#project-github',
  },
  {
    id: 6,
    title: 'Mamal',
    date: '2021-03-01',
    tech: ['Typescript', 'Node'],
    description:
      'consectetur adipisicing elit. Vitae quisquam iste tempora, quas eos, sit quam aut animi non blanditiisem',
    img: 'https://images.unsplash.com/photo-1603897178457-f87e0bf8fd53?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjV8fG1hbWFsfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    src: '#project-demo',
    src_github: '#project-github',
  },
]
